CREATE USER ADMINCITAS IDENTIFIED BY abc
DEFAULT TABLESPACE SYSTEM 
QUOTA 20M ON SYSTEM;

--ALTER USER ADMINUNIVERSIDAD QUOTA UNLIMITED ON SYSTEM

CREATE ROLE ROLEADMINCITAS ;

GRANT CREATE SESSION TO ROLEADMINCITAS  WITH ADMIN OPTION;
GRANT CREATE USER TO ROLEADMINCITAS  WITH ADMIN OPTION;
GRANT CREATE TABLE TO ROLEADMINCITAS  WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO ROLEADMINCITAS  WITH ADMIN OPTION;
GRANT CREATE ROLE TO ROLEADMINCITAS  WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO ROLEADMINCITAS  WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO ROLEADMINCITAS  WITH ADMIN OPTION;

GRANT ROLEADMINCITAS TO ADMINCITAS